Repository Kumoh-talk/kumoh-talk-Backend, pull requests merged in 2024-08, with the labels that each got.

#66 fix : ci workflows
  .github/workflows/ci-gradle-build.yml
Labels: 🛠️ Setting

#69 [#54] 세미나 게시판 API 설계 및 컨벤션 변경에 따른 리팩터링 반영
  src/main/java/com/example/demo/domain/board/Repository/BoardCategoryRepository.java
  src/main/java/com/example/demo/domain/board/Repository/BoardRepository.java
  src/main/java/com/example/demo/domain/board/Repository/LikeRepository.java
  src/main/java/com/example/demo/domain/board/Repository/ViewRepository.java
  src/main/java/com/example/demo/domain/board/controller/BoardController.java
  src/main/java/com/example/demo/domain/board/domain/dto/page/PageInfo.java
  src/main/java/com/example/demo/domain/board/domain/dto/page/PageSort.java
  src/main/java/com/example/demo/domain/board/domain/dto/page/PageTitleInfo.java
  src/main/java/com/example/demo/domain/board/domain/dto/request/BoardCreateRequest.java
  src/main/java/com/example/demo/domain/board/domain/dto/request/BoardUpdateRequest.java
  src/main/java/com/example/demo/domain/board/domain/dto/response/BoardInfoResponse.java
  src/main/java/com/example/demo/domain/board/domain/dto/response/BoardPageResponse.java
  src/main/java/com/example/demo/domain/board/domain/dto/vo/Status.java
  src/main/java/com/example/demo/domain/board/domain/dto/vo/Tag.java
  src/main/java/com/example/demo/domain/board/domain/entity/Board.java
  src/main/java/com/example/demo/domain/board/domain/entity/BoardCategory.java
  src/main/java/com/example/demo/domain/board/domain/entity/Category.java
  src/main/java/com/example/demo/domain/board/domain/entity/Like.java
  src/main/java/com/example/demo/domain/board/domain/entity/View.java
  src/main/java/com/example/demo/domain/board/domain/page/PageSort.java
  src/main/java/com/example/demo/domain/board/service/BoardService.java
  src/main/java/com/example/demo/domain/board/service/service/BoardCommandService.java
  src/main/java/com/example/demo/domain/board/service/service/BoardQueryService.java
  src/main/java/com/example/demo/domain/board/service/service/LikeService.java
  src/main/java/com/example/demo/domain/board/service/service/ViewIncreaseBasicService.java
  src/main/java/com/example/demo/domain/board/service/service/ViewIncreaseService.java
  src/main/java/com/example/demo/domain/board/service/usecase/BoardUseCase.java
  src/main/java/com/example/demo/domain/file/controller/FileController.java
  src/main/java/com/example/demo/domain/file/domain/entity/File.java
  src/main/java/com/example/demo/domain/file/service/FileService.java
  src/main/java/com/example/demo/domain/user/domain/User.java
  src/main/java/com/example/demo/global/base/exception/ErrorCode.java
  src/test/java/com/example/demo/base/RepositoryTest.java
  src/test/java/com/example/demo/domain/board/Repository/BoardCategoryRepositoryTest.java
  src/test/java/com/example/demo/domain/board/Repository/BoardRepositoryTest.java
Labels: 🚀 Enhancement, ♻️ Refactor

#71 [#70] 세미나 게시물 관련 조회 및 좋아요 삭제 API 구현
  src/main/java/com/example/demo/domain/board/Repository/BoardRepository.java
  src/main/java/com/example/demo/domain/board/Repository/CategoryRepository.java
  src/main/java/com/example/demo/domain/board/Repository/LikeRepository.java
  src/main/java/com/example/demo/domain/board/controller/BoardController.java
  src/main/java/com/example/demo/domain/board/controller/CategoryController.java
  src/main/java/com/example/demo/domain/board/controller/LikeController.java
  src/main/java/com/example/demo/domain/board/domain/dto/page/PageInfo.java
  src/main/java/com/example/demo/domain/board/domain/dto/page/PageSort.java
  src/main/java/com/example/demo/domain/board/domain/dto/page/PageTitleInfo.java
  src/main/java/com/example/demo/domain/board/domain/dto/response/BoardPageResponse.java
  src/main/java/com/example/demo/domain/board/domain/dto/response/BoardTitleInfoResponse.java
  src/main/java/com/example/demo/domain/board/domain/entity/Board.java
  src/main/java/com/example/demo/domain/board/service/service/BoardQueryService.java
  src/main/java/com/example/demo/domain/board/service/service/CategoryQueryService.java
  src/main/java/com/example/demo/domain/board/service/service/LikeService.java
  src/main/java/com/example/demo/domain/board/service/usecase/BoardUseCase.java
  src/main/java/com/example/demo/domain/board/service/usecase/CategoryUseCase.java
  src/main/java/com/example/demo/domain/board/service/usecase/LikeUseCase.java
  src/main/java/com/example/demo/global/base/exception/ErrorCode.java
  src/main/resources/application.yml
Labels: 🚀 Enhancement, ♻️ Refactor

#77 [#76] 뉴스레터, 세미나 신청 api 기능 개발
  src/main/java/com/example/demo/domain/newsletter/controller/NewsletterController.java
  src/main/java/com/example/demo/domain/newsletter/domain/Newsletter.java
  src/main/java/com/example/demo/domain/newsletter/domain/dto/request/NewsletterSubscribeRequest.java
  src/main/java/com/example/demo/domain/newsletter/domain/dto/request/NewsletterUpdateEmailRequest.java
  src/main/java/com/example/demo/domain/newsletter/domain/dto/request/NewsletterUpdateNotifyRequest.java
  src/main/java/com/example/demo/domain/newsletter/domain/dto/response/NewsletterInfo.java
  src/main/java/com/example/demo/domain/newsletter/repository/NewsletterRepository.java
  src/main/java/com/example/demo/domain/newsletter/service/NewsletterService.java
  src/main/java/com/example/demo/domain/seminar_application/controller/SeminarApplicationController.java
  src/main/java/com/example/demo/domain/seminar_application/domain/SeminarApplication.java
  src/main/java/com/example/demo/domain/seminar_application/domain/dto/request/SeminarApplicationRequest.java
  src/main/java/com/example/demo/domain/seminar_application/domain/dto/request/SeminarApplicationUpdateRequest.java
  src/main/java/com/example/demo/domain/seminar_application/domain/dto/response/SeminarApplicationInfo.java
  src/main/java/com/example/demo/domain/seminar_application/repository/SeminarApplicationRepository.java
  src/main/java/com/example/demo/domain/seminar_application/service/SeminarApplicationService.java
  src/main/java/com/example/demo/domain/user/controller/UserController.java
  src/main/java/com/example/demo/domain/user/domain/User.java
  src/main/java/com/example/demo/domain/user_addtional_info/service/UserAdditionalInfoService.java
  src/main/java/com/example/demo/global/base/exception/ErrorCode.java
  src/main/java/com/example/demo/global/config/auth/SecurityConfig.java
  src/test/java/com/example/demo/base/ControllerTest.java
Labels: 🚀 Enhancement
