Repository Kumoh-talk/kumoh-talk-Backend, pull requests merged in 2024-04, with the labels that each got.

#35 [#33] User / global 리팩토링
  src/main/java/com/example/demo/domain/auth/api/AuthController.java
  src/main/java/com/example/demo/domain/auth/application/AuthService.java
  src/main/java/com/example/demo/domain/auth/dto/request/JoinRequest.java
  src/main/java/com/example/demo/domain/board/Repository/BoardRepository.java
  src/main/java/com/example/demo/domain/board/controller/BoardController.java
  src/main/java/com/example/demo/domain/board/domain/page/PageTitleInfo.java
  src/main/java/com/example/demo/domain/board/domain/request/BoardRequest.java
  src/main/java/com/example/demo/domain/board/service/BoardService.java
  src/main/java/com/example/demo/domain/calendar/domain/Calendar.java
  src/main/java/com/example/demo/domain/user/domain/User.java
  src/main/java/com/example/demo/domain/user/domain/vo/Role.java
  src/main/java/com/example/demo/domain/user/domain/vo/Status.java
  src/main/java/com/example/demo/domain/user/domain/vo/Track.java
  src/main/java/com/example/demo/domain/user/dto/request/UserUpdateRequest.java
  src/main/java/com/example/demo/domain/user/dto/response/UserInfoResponse.java
  src/main/java/com/example/demo/domain/user/dto/response/UserUpdateResponse.java
  src/main/java/com/example/demo/global/auth/token/application/TokenProvider.java
  src/main/java/com/example/demo/global/auth/token/domain/RefreshToken.java
  src/main/java/com/example/demo/global/auth/token/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/example/demo/global/auth/token/filter/JwtFilter.java
  src/main/java/com/example/demo/global/auth/token/repository/RefreshTokenRepository.java
  src/main/java/com/example/demo/global/base/domain/BaseEntity.java
  src/main/java/com/example/demo/global/base/dto/ErrorResponse.java
  src/main/java/com/example/demo/global/base/exception/ErrorCode.java
  src/main/java/com/example/demo/global/base/exception/GlobalExceptionHandler.java
  src/main/java/com/example/demo/global/config/auth/SecurityConfig.java
  src/main/resources/application-security.yml
  src/test/java/com/example/demo/domain/auth/api/AuthControllerTest.java
  src/test/java/com/example/demo/domain/user/api/UserControllerTest.java
Labels: ♻️ Refactor

#39 [#37] board update 로직 구현 및 Service Test 코드 작성
  src/main/java/com/example/demo/domain/board/controller/BoardController.java
  src/main/java/com/example/demo/domain/board/domain/entity/Board.java
  src/main/java/com/example/demo/domain/board/domain/request/BoardRequest.java
  src/main/java/com/example/demo/domain/board/domain/response/BoardInfoResponse.java
  src/main/java/com/example/demo/domain/board/service/BoardService.java
  src/main/java/com/example/demo/domain/category/domain/entity/BoardCategory.java
  src/main/java/com/example/demo/domain/category/repository/BoardCategoryRepository.java
  src/main/java/com/example/demo/domain/user/domain/User.java
  src/test/java/com/example/demo/domain/board/Repository/BoardRepositoryTest.java
  src/test/java/com/example/demo/domain/board/service/BoardServiceTest.java
Labels: 🚀 Enhancement, ✅ Test, ♻️ Refactor

#41 [#40] 로그인 기능 구현
  build.gradle
  src/main/java/com/example/demo/domain/auth/api/AuthController.java
  src/main/java/com/example/demo/domain/auth/application/AuthService.java
  src/main/java/com/example/demo/domain/auth/application/CustomUserDetailsService.java
  src/main/java/com/example/demo/domain/auth/domain/UserContext.java
  src/main/java/com/example/demo/domain/auth/dto/request/JoinRequest.java
  src/main/java/com/example/demo/domain/auth/dto/request/LoginRequest.java
  src/main/java/com/example/demo/domain/auth/security/CustomAccessDeniedHandler.java
  src/main/java/com/example/demo/domain/auth/security/CustomAuthenticationEntryPoint.java
  src/main/java/com/example/demo/domain/auth/security/LoginAuthenticationFailureHandler.java
  src/main/java/com/example/demo/domain/auth/security/LoginAuthenticationFilter.java
  src/main/java/com/example/demo/domain/auth/security/LoginAuthenticationProvider.java
  src/main/java/com/example/demo/domain/auth/security/LoginAuthenticationSuccessHandler.java
  src/main/java/com/example/demo/domain/board/controller/BoardController.java
  src/main/java/com/example/demo/domain/comment/controller/CommentController.java
  src/main/java/com/example/demo/domain/comment/domain/response/CommentInfoResponse.java
  src/main/java/com/example/demo/domain/file/controller/FileController.java
  src/main/java/com/example/demo/domain/user/api/UserController.java
  src/main/java/com/example/demo/domain/user/application/UserService.java
  src/main/java/com/example/demo/domain/user/domain/User.java
  src/main/java/com/example/demo/domain/user/domain/vo/Role.java
  src/main/java/com/example/demo/global/base/exception/ErrorCode.java
  src/main/java/com/example/demo/global/base/exception/GlobalExceptionHandler.java
  src/main/java/com/example/demo/global/config/auth/SecurityConfig.java
  src/main/resources/application-security.yml
Labels: ♻️ Refactor, 🛠️ Setting
