Repository Kumoh-talk/kumoh-talk-Backend, pull requests merged in 2024-03, with the labels that each got.

#17 [#16] User CRU 기능
  src/docs/asciidoc/auth.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/user.adoc
  src/main/java/com/example/demo/domain/auth/dto/request/JoinRequest.java
  src/main/java/com/example/demo/domain/user/api/UserController.java
  src/main/java/com/example/demo/domain/user/application/UserService.java
  src/main/java/com/example/demo/domain/user/domain/User.java
  src/main/java/com/example/demo/domain/user/dto/request/UserPasswordUpdateRequest.java
  src/main/java/com/example/demo/domain/user/dto/request/UserUpdateRequest.java
  src/main/java/com/example/demo/domain/user/dto/response/UserInfoResponse.java
  src/main/java/com/example/demo/domain/user/dto/response/UserUpdateResponse.java
  src/main/java/com/example/demo/global/auth/token/application/TokenProvider.java
  src/main/java/com/example/demo/global/auth/token/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/example/demo/global/auth/token/exception/ExpiredTokenException.java
  src/main/java/com/example/demo/global/auth/token/exception/InvalidTokenException.java
  src/main/java/com/example/demo/global/auth/token/exception/NotSupportedTokenException.java
  src/main/java/com/example/demo/global/auth/token/exception/TokenException.java
  src/main/java/com/example/demo/global/auth/token/filter/ExceptionHandlerFilter.java
  src/main/java/com/example/demo/global/auth/token/filter/JwtFilter.java
  src/main/java/com/example/demo/global/base/domain/BaseEntity.java
  src/main/java/com/example/demo/global/base/dto/ErrorResponse.java
  src/main/java/com/example/demo/global/base/exception/ErrorCode.java
  src/main/java/com/example/demo/global/config/auth/SecurityConfig.java
  src/test/java/com/example/demo/base/ControllerTest.java
  src/test/java/com/example/demo/domain/user/api/UserControllerTest.java
Labels: 🚀 Enhancement, ✅ Test, 🛠️ Setting

#19 [#18] Refresh Token 구현
  src/docs/asciidoc/auth.adoc
  src/main/java/com/example/demo/domain/auth/api/AuthController.java
  src/main/java/com/example/demo/domain/auth/application/AuthService.java
  src/main/java/com/example/demo/domain/auth/dto/response/LoginResponse.java
  src/main/java/com/example/demo/global/auth/token/application/TokenProvider.java
  src/main/java/com/example/demo/global/auth/token/domain/RefreshToken.java
  src/main/java/com/example/demo/global/auth/token/filter/JwtFilter.java
  src/main/java/com/example/demo/global/auth/token/repository/RefreshTokenRepository.java
  src/main/java/com/example/demo/global/base/exception/ErrorCode.java
  src/main/java/com/example/demo/global/config/auth/SecurityConfig.java
  src/main/java/com/example/demo/global/config/web/WebConfig.java
  src/main/java/com/example/demo/global/utils/CookieUtil.java
  src/main/java/com/example/demo/global/utils/HttpServletUtil.java
  src/test/java/com/example/demo/domain/auth/api/AuthControllerTest.java
Labels: 🚀 Enhancement, 🛠️ Setting

#21 [#20] 게시판 관련 CRUD 추가
  src/main/java/com/example/demo/domain/post/controller/PostController.java
  src/main/java/com/example/demo/domain/post/domain/request/PostUpdateRequest.java
  src/main/java/com/example/demo/domain/post/domain/response/PostInfoResponse.java
  src/main/java/com/example/demo/domain/post/service/PostService.java
Labels: 🛠️ Setting

#23 [#22] QnA 간단한 CRUD 구현
  src/main/java/com/example/demo/domain/announcement/domain/Announcement.java
  src/main/java/com/example/demo/domain/post/Repository/PostRepository.java
  src/main/java/com/example/demo/domain/post/comment/domain/Comment.java
  src/main/java/com/example/demo/domain/post/controller/PostController.java
  src/main/java/com/example/demo/domain/post/domain/File.java
  src/main/java/com/example/demo/domain/post/domain/Post.java
  src/main/java/com/example/demo/domain/post/domain/request/PostRequest.java
  src/main/java/com/example/demo/domain/post/domain/response/PostInfoResponse.java
  src/main/java/com/example/demo/domain/post/post_qna/controller/QnaController.java
  src/main/java/com/example/demo/domain/post/post_qna/domain/Post_Qna.java
  src/main/java/com/example/demo/domain/post/post_qna/domain/request/QnaRequest.java
  src/main/java/com/example/demo/domain/post/post_qna/domain/response/QnaInfoResponse.java
  src/main/java/com/example/demo/domain/post/post_qna/repository/QnaRepository.java
  src/main/java/com/example/demo/domain/post/post_qna/service/QnaService.java
  src/main/java/com/example/demo/domain/post/service/PostService.java
  src/main/java/com/example/demo/domain/user/domain/User.java
  src/test/java/com/example/demo/domain/post/Repository/PostRepositoryTest.java
Labels: 🚀 Enhancement, ♻️ Refactor
