Repository Kumoh-talk/kumoh-talk-Backend, pull requests merged in 2025-03, with the labels that each got.

#138 kakao_account을 반환하지 않아 발생하는 null 오류 수정
  src/main/java/com/example/demo/global/oauth/user/kakao/KakaoOAuth2UserInfo.java
Labels: 🐛 Bug

#139 신고 도메인 패키지 구조 리팩터링
  src/main/java/com/example/demo/application/report/api/ReportAdminApi.java
  src/main/java/com/example/demo/application/report/api/ReportApi.java
  src/main/java/com/example/demo/application/report/controller/ReportAdminController.java
  src/main/java/com/example/demo/application/report/controller/ReportController.java
  src/main/java/com/example/demo/application/report/dto/response/ReportResponse.java
  src/main/java/com/example/demo/application/report/dto/response/ReportedCommentInfoResponse.java
  src/main/java/com/example/demo/domain/newsletter/client/DiscordNewsletterClient.java
  src/main/java/com/example/demo/domain/report/client/DiscordMessage.java
  src/main/java/com/example/demo/domain/report/client/DiscordReportClient.java
  src/main/java/com/example/demo/domain/report/domain/ReportInfo.java
  src/main/java/com/example/demo/domain/report/domain/ReportedCommentInfo.java
  src/main/java/com/example/demo/domain/report/domain/dto/ReportResponse.java
  src/main/java/com/example/demo/domain/report/implement/ReportReader.java
  src/main/java/com/example/demo/domain/report/implement/ReportWriter.java
  src/main/java/com/example/demo/domain/report/repository/ReportRepository.java
  src/main/java/com/example/demo/domain/report/service/ReportService.java
  src/main/java/com/example/demo/global/base/exception/ErrorCode.java
  src/main/java/com/example/demo/infra/comment/entity/BoardComment.java
  src/main/java/com/example/demo/infra/comment/entity/Comment.java
  src/main/java/com/example/demo/infra/comment/entity/RecruitmentBoardComment.java
  src/main/java/com/example/demo/infra/report/entity/Report.java
  src/main/java/com/example/demo/infra/report/repository/ReportJpaRepository.java
  src/main/java/com/example/demo/infra/report/repository/ReportRepositoryImpl.java
Labels: ♻️ Refactor

#142 세미나/공지사항 게시물 삭제시 좋아요 일괄 soft 삭제 구현 추가 및 board content 데이터 타입 변경
  src/main/java/com/example/demo/domain/board/service/implement/LikeHandler.java
  src/main/java/com/example/demo/domain/board/service/repository/LikeRepository.java
  src/main/java/com/example/demo/domain/board/service/service/BoardService.java
  src/main/java/com/example/demo/infra/board/entity/Board.java
  src/main/java/com/example/demo/infra/board/repository/LikeRepositoryImpl.java
Labels: 🐛 Bug, 🚀 Enhancement

#143 UserAdditionalIfo 필드 수정
  src/main/java/com/example/demo/infra/user_additional_info/entity/UserAdditionalInfo.java
Labels: 🐛 Bug

#145 세미나 신청 패키지 구조 리팩터링
  src/main/java/com/example/demo/application/seminar_application/api/SeminarApplicationAdminApi.java
  src/main/java/com/example/demo/application/seminar_application/api/SeminarApplicationApi.java
  src/main/java/com/example/demo/application/seminar_application/controller/SeminarApplicationAdminController.java
  src/main/java/com/example/demo/application/seminar_application/controller/SeminarApplicationController.java
  src/main/java/com/example/demo/application/seminar_application/dto/request/SeminarApplicationRequest.java
  src/main/java/com/example/demo/application/seminar_application/dto/request/SeminarApplicationUpdateRequest.java
  src/main/java/com/example/demo/application/seminar_application/dto/response/SeminarApplicationResponse.java
  src/main/java/com/example/demo/domain/seminar_application/domain/SeminarApplication.java
  src/main/java/com/example/demo/domain/seminar_application/domain/dto/request/SeminarApplicationRequest.java
  src/main/java/com/example/demo/domain/seminar_application/domain/dto/request/SeminarApplicationUpdateRequest.java
  src/main/java/com/example/demo/domain/seminar_application/domain/dto/response/SeminarApplicationInfo.java
  src/main/java/com/example/demo/domain/seminar_application/entity/SeminarApplicant.java
  src/main/java/com/example/demo/domain/seminar_application/entity/SeminarApplicationInfo.java
  src/main/java/com/example/demo/domain/seminar_application/entity/SeminarContent.java
  src/main/java/com/example/demo/domain/seminar_application/implement/SeminarApplicationReader.java
  src/main/java/com/example/demo/domain/seminar_application/implement/SeminarApplicationWriter.java
  src/main/java/com/example/demo/domain/seminar_application/repository/SeminarApplicationRepository.java
  src/main/java/com/example/demo/domain/seminar_application/service/SeminarApplicationAdminService.java
  src/main/java/com/example/demo/domain/seminar_application/service/SeminarApplicationService.java
  src/main/java/com/example/demo/infra/seminar_application/entity/SeminarApplication.java
  src/main/java/com/example/demo/infra/seminar_application/repository/SeminarApplicationJpaRepository.java
  src/main/java/com/example/demo/infra/seminar_application/repository/SeminarApplicationRepositoryImpl.java
  src/main/java/com/example/demo/infra/user/entity/User.java
Labels: ♻️ Refactor

#146 Flyway 도입
  .github/workflows/develop-cicd-gradle.yml
  .github/workflows/prod-cicd.yml
  build.gradle
  src/main/java/com/example/demo/application/comment/dto/response/CommentResponse.java
  src/main/java/com/example/demo/domain/comment/entity/CommentListInfo.java
  src/main/java/com/example/demo/domain/comment/implement/comment/AbstractCommentHandler.java
  src/main/java/com/example/demo/domain/comment/repository/CommentRepository.java
  src/main/java/com/example/demo/domain/comment/service/AbstractCommentService.java
  src/main/java/com/example/demo/global/config/migration/FlywayConfig.java
  src/main/java/com/example/demo/infra/comment/repository/impl/AbstractCommentRepositoryImpl.java
  src/main/java/com/example/demo/infra/comment/repository/jpa/BoardCommentJpaRepository.java
  src/main/java/com/example/demo/infra/comment/repository/jpa/CommentJpaRepository.java
  src/main/java/com/example/demo/infra/comment/repository/jpa/RecruitmentBoardCommentJpaRepository.java
  src/main/java/com/example/demo/infra/recruitment_board/repository/querydsl/QueryDslRecruitmentBoardRepositoryImpl.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/db/flyway/Dockerfile_flyway
  src/main/resources/db/flyway/HowToMigration.md
  src/main/resources/db/flyway/flyway.sh
  src/main/resources/db/migration/V20250314231509__init.sql
  src/test/java/com/example/demo/migration/FlywayMigrationTest.java
  src/test/resources/application-test.yml
Labels: ✅ Test, 🙏 CI/CD
